"""companies.financial_currency

Revision ID: b1ae11760846
Revises: e11a21459588
Create Date: 2026-09-05 13:00:05.800067
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = 'b1ae11760846'
down_revision: str | None = 'e11a21459588'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('financial_currency', sa.String(length=3), server_default='INR', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('companies', 'financial_currency')
    # ### end Alembic commands ###
