"""initial schema: companies, prices, facts

Revision ID: e11a21459588
Revises: 
Create Date: 2026-09-05 12:55:48.296477
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = 'e11a21459588'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('ticker', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('sector', sa.String(length=50), nullable=False),
    sa.Column('yf_symbol', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('ticker'),
    sa.UniqueConstraint('yf_symbol')
    )
    op.create_index(op.f('ix_companies_sector'), 'companies', ['sector'], unique=False)
    op.create_table('facts',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('ticker', sa.String(length=20), nullable=False),
    sa.Column('statement', sa.String(length=30), nullable=False),
    sa.Column('concept', sa.String(length=120), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('value', sa.Numeric(precision=30, scale=4), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.Column('source', sa.String(length=40), nullable=False),
    sa.Column('ingested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ticker'], ['companies.ticker'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticker', 'statement', 'concept', 'period_end', name='uq_facts_identity')
    )
    op.create_index(op.f('ix_facts_concept'), 'facts', ['concept'], unique=False)
    op.create_index(op.f('ix_facts_period_end'), 'facts', ['period_end'], unique=False)
    op.create_index(op.f('ix_facts_statement'), 'facts', ['statement'], unique=False)
    op.create_index(op.f('ix_facts_ticker'), 'facts', ['ticker'], unique=False)
    op.create_table('prices',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('ticker', sa.String(length=20), nullable=False),
    sa.Column('trade_date', sa.Date(), nullable=False),
    sa.Column('open', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('high', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('low', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('close', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('adj_close', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('volume', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['ticker'], ['companies.ticker'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticker', 'trade_date', name='uq_prices_ticker_date')
    )
    op.create_index(op.f('ix_prices_ticker'), 'prices', ['ticker'], unique=False)
    op.create_index('ix_prices_ticker_date', 'prices', ['ticker', 'trade_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_prices_ticker_date', table_name='prices')
    op.drop_index(op.f('ix_prices_ticker'), table_name='prices')
    op.drop_table('prices')
    op.drop_index(op.f('ix_facts_ticker'), table_name='facts')
    op.drop_index(op.f('ix_facts_statement'), table_name='facts')
    op.drop_index(op.f('ix_facts_period_end'), table_name='facts')
    op.drop_index(op.f('ix_facts_concept'), table_name='facts')
    op.drop_table('facts')
    op.drop_index(op.f('ix_companies_sector'), table_name='companies')
    op.drop_table('companies')
    # ### end Alembic commands ###
