"""elements table

Revision ID: e72036aab5e4
Revises: f35f3fd57fb0
Create Date: 2026-09-05 13:27:24.851664
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql
revision: str = 'e72036aab5e4'
down_revision: str | None = 'f35f3fd57fb0'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('elements',
    sa.Column('element_id', sa.String(length=120), nullable=False),
    sa.Column('document_id', sa.String(length=80), nullable=False),
    sa.Column('page', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('table_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('image_path', sa.Text(), nullable=True),
    sa.Column('bbox', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.document_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('element_id')
    )
    op.create_index('ix_elements_doc_page', 'elements', ['document_id', 'page'], unique=False)
    op.create_index(op.f('ix_elements_document_id'), 'elements', ['document_id'], unique=False)
    op.create_index(op.f('ix_elements_page'), 'elements', ['page'], unique=False)
    op.create_index(op.f('ix_elements_type'), 'elements', ['type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_elements_type'), table_name='elements')
    op.drop_index(op.f('ix_elements_page'), table_name='elements')
    op.drop_index(op.f('ix_elements_document_id'), table_name='elements')
    op.drop_index('ix_elements_doc_page', table_name='elements')
    op.drop_table('elements')
    # ### end Alembic commands ###
