"""documents table

Revision ID: f35f3fd57fb0
Revises: b1ae11760846
Create Date: 2026-09-05 13:20:28.853339
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = 'f35f3fd57fb0'
down_revision: str | None = 'b1ae11760846'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documents',
    sa.Column('document_id', sa.String(length=80), nullable=False),
    sa.Column('ticker', sa.String(length=20), nullable=False),
    sa.Column('doc_type', sa.String(length=40), nullable=False),
    sa.Column('fiscal_year', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('local_path', sa.Text(), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('n_pages', sa.Integer(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ticker'], ['companies.ticker'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('document_id'),
    sa.UniqueConstraint('ticker', 'doc_type', 'fiscal_year', name='uq_documents_identity')
    )
    op.create_index(op.f('ix_documents_doc_type'), 'documents', ['doc_type'], unique=False)
    op.create_index(op.f('ix_documents_fiscal_year'), 'documents', ['fiscal_year'], unique=False)
    op.create_index(op.f('ix_documents_ticker'), 'documents', ['ticker'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_documents_ticker'), table_name='documents')
    op.drop_index(op.f('ix_documents_fiscal_year'), table_name='documents')
    op.drop_index(op.f('ix_documents_doc_type'), table_name='documents')
    op.drop_table('documents')
    # ### end Alembic commands ###
